### ISSUE TITLE
Filter fails Github Actions v2 jobs

### ISSUE THREAD

**Issue by Djiit** [actions/bin#66]
Before migrating to the new YML syntax, the build was `Neutral`. Now, filter fails the build when, e.g., the branch is not "master" (or whatever filter you have).

Is this wanted ?

Thanks

**Comment by peaceiris** [comment]
How about using the built-in branch filtering options? With GitHub Actions beta v2, we can filter branches using the built-in options without the filter actions.

[Filtering for specific branches | Configuring a workflow - GitHub Help](https://help.github.com/en/articles/configuring-a-workflow#filtering-for-specific-branches)

**Comment by Atrox** [comment]
What if I only want to run the workflow on tags to build a release?

This sadly does not work:
```yaml
on:
  push:
    tags:
      - v*
```

**Comment by Djiit** [comment]
Ah! Same use case here

--
Julien

**Comment by 0xdeafcafe** [comment]
I'm having this issue, but I'm not using it to only run on master, but to not run if the branch has been deleted (to deal with the double running on squash-merges). Is there any workaround for that?

**Comment by peaceiris** [comment]
> I'm having this issue, but I'm not using it to only run on master, but to not run if the branch has been deleted (to deal with the double running on squash-merges). Is there any workaround for that?

You can use ` if: github.event.deleted == false`.

```yaml
jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      if: github.event.deleted == false
      env:
        DOCKER_IMAGE: ${{ github.repository }}:${{ github.sha }}
      run: |
        docker build . --file Dockerfile --tag ${DOCKER_IMAGE} &&
        docker run ${DOCKER_IMAGE} cat /etc/lsb-release ||
        (echo -e "\e[31m[${GITHUB_WORKFLOW}] failed to build\e[m" && exit 1)
```

**Comment by njzjz** [comment]
I use `if: github.ref == 'refs/heads/master'` instead and it works.

**Comment by statik** [comment]
I'm using

**Comment by fooey** [comment]
> What if I only want to run the workflow on tags to build a release?
> 
> This sadly does not work:
> 
> ```yaml
> on:
>   push:
>     tags:
>       - v*
> ```

The new tag filtering doesn't seem to be working correctly at all

For example, we have some actions setup for alpha, beta, staging, and production that look like 

Dev:
```yaml
on:
  push:
    tags:
      - 'v*'
      - 'v*.*.*-alpha.*'
    branches:
      - 'refs/tags/*'
      - '!refs/heads/*'
```

Production:
```yaml
on:
  push:
    tags:
      - 'v*'
      - '!v*.*.*-.*'
    branches:
      - 'refs/tags/*'
      - '!refs/heads/*'
```

However, as we found out today, pushing a tag with `v2019.7.0-beta.32` triggered all 4 of our deploy scripts, including production 😱 

These exact same patterns worked perfectly fine with the old filter actions
