### ISSUE TITLE
v2 actions: How to filter release events by type?

### ISSUE THREAD

**Issue by miangraham** [actions/bin#68]
Here is the thing I did in v1 to prevent running multiple builds when hitting Publish on a new release in v1:

```yml
- name: Filter for New Release
  uses: actions/bin/filter@0dbb077f64d0ec1068a644d25c71b1db66148a24
    with:
      args: action 'created|edited'
```

The above worked fine, but now that I'm migrated to v2 and the rec seems to be to use the built-in filter, how do I do this with that?

Guessing at undocumented (NYI?) behavior has me trying things like the below but I haven't hit on anything that works yet.
```yml
on:
  release:
    action:
    - created
    - edited
```

Suggestions appreciated!

**Comment by peaceiris** [comment]
How about this?

```yaml
steps:
  - name: Release
     if: github.event_name == 'release' && github.event.action == 'published'
     run: echo "release action"
```

- [steps.if | Workflow syntax for GitHub Actions - GitHub Help](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsif-1)
- [Events that trigger workflows - GitHub Help](https://help.github.com/en/articles/events-that-trigger-workflows)
