### ISSUE TITLE
cURL action with multiple args

### ISSUE THREAD

**Issue by pzurek** [actions/bin#69]
I have an action where I need to pass multiple arguments to cURL, which I imagine is a fairly common use-case. I have a problem achieving this with the new YAML syntax.
I have something like this:

```YAML
on: push
name: Make a cURL request
jobs:
  docs-list:
    runs-on: ubuntu-latest
    steps:
      - name: curl request
        uses: actions/bin/curl@master
        env:
          TOKEN: ${{ secrets.SOME_TOKEN }}
          URL: https://example.io/projects/17493
        with:
          args: -H "Authorization: Bearer $TOKEN" $URL
```
I've tried different combinations of quotes (for every argument and wrapping all of them), wrapping everything in `[]` and separating with a `,`. No matter what I do I end up with either an error or the action trying to use the token as the URL.
Can someone please update the docs for cURL with the appropriate syntax?

**Comment by peaceiris** [comment]
```
on: push
name: Make a cURL request
jobs:
  docs-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: curl request
        env:
          TOKEN: ${{ secrets.SOME_TOKEN }}
          URL: https://example.io/projects/17493
        run: curl -H "Authorization: Bearer $TOKEN" $URL
```
