### ISSUE TITLE
How to check if pull request is merged without giving failure status check

### ISSUE THREAD

**Issue by TarekAS** [actions/bin#71]
I have a job that only runs when the pull request is merged. Using this:
```
- name: merged-prs-filter
  uses: actions/bin/filter@master
  with:
    args: merged true
```
However, this always gives a failed status check on my PR. This should be neutral, or succeed without running subsequent steps.
