### ISSUE TITLE
Multiline arguments

### ISSUE THREAD

**Issue by hazcod** [actions/bin#72]
Hi, how can one use multiline arguments with the `bin` runner?

e.g.
```
    - name: Decrypt secrets
      uses: actions/bin/sh@master
      with:
        args: |
          if [ -f "terraform.tfstate" ]; then
            echo "State found in repo!"
            exit 1
          fi
          if [ ! -f "terraform.tfstate.enc" ]; then
            echo "No state found, starting fresh (!)"
            exit 0
          fi
          openssl enc -aes-256-cbc -salt -in terraform.tfstate.enc -out terraform.tfstate -d -pass env:STATE_PASSWORD
          rm terraform.tfstate.enc
      env:
        STATE_PASSWORD: ${{ secrets.TF_STATE_SECRET }}
```

**Comment by peaceiris** [comment]
```yaml
jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      run: |
        shellcheck ./entrypoint.sh
        echo "All task done!"
```
